### ISSUE TITLE
Markdown issues

### ISSUE THREAD

**Issue by rizwankce** [GitHawkApp/GitHawk#1680]
From the app

![GitHawk Upload by rizwankce](https://i.imgur.com/2xnt7KM.jpg)

From the browser 
![GitHawk Upload by rizwankce](https://i.imgur.com/fUzgUlU.jpg)

Edit:

Link to the github PR https://github.com/artsy/artsy.github.io/pull/423
<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SD10** [comment]
This may be a naive question but I'm genuinely curious about the state of our markdown parser dependency. Would a better solution be to wrap GitHub's fork of CMark in a Swift API?

**Comment by rnystrom** [comment]
@SD10 any details on it? I haven’t seen it before. I remember investigating cmark before and it wasn’t an option, can’t remember the specifics.

Note that our parsing lib was written by a GitHub engineer originally.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SD10** [comment]
@rnystrom Yeah the GFM spec is amazingly detailed. I was considering writing a parser of my own to follow that spec in Swift but decided to spend my time other places. If I could wrap GitHub's fork for Swift that would save me from having to reinvent the wheel. 

I'll explore this more as well with no concrete time frame 😓

**Comment by SD10** [comment]
@rnystrom Awesome! Thanks for taking the initiative. I'd love to take a look at the WIP. This could eliminate a whole category of issues for GitHawk both present and future

**Comment by rnystrom** [comment]
[Here's the WIP](https://github.com/GitHawkApp/cmark-gfm-swift). Probably the most important part is adding a custom extension, e.g. the one I wrote to handle [mentions](https://github.com/GitHawkApp/cmark-gfm-swift/blob/master/cmark-gfm-swift/Classes/mention.c). We'll need another one to do checkmarks. 

All of the URL handling/shortening can be done outside of the lib. _However_ the auto shortlink (e.g. repo/name#123) can't. There needs to be a solution for that.

What I'm thinking of doing is this:

1. cmark + extensions to build c AST
2. Use enums, inspired by [this lib](https://github.com/chriseidhof/commonmark-swift) to convert to typed Swift AST
3. Flatten to node stream
  - Things like text, quotes, images, html, tables
4. Map nodes to GitHawk's models

That breaks things apart pretty nicely making each component testable.

**Comment by SD10** [comment]
> Probably the most important part is adding a custom extension, e.g. the one I wrote to handle mentions.

@rnystrom Mentions were not already handled? Surprising.

**Comment by rnystrom** [comment]
@SD10 ya it wasn’t. Finished a checkbox extension last night as well. Should be in place to start using.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
@SD10 I know this Issue is off topic, but using this as my place to give status-updates on the cmark integration:

- I built a mentions and checkbox extension on top of GitHub's cmark fork (this is worth a blog post)
- Our cmark-gfm fork + extensions are in [this repo](https://github.com/GitHawkApp/cmark-gfm-swift)
- Pushed WIP to [this branch](https://github.com/GitHawkApp/GitHawk/tree/cmark)
- Building our list models happens [here](https://github.com/GitHawkApp/GitHawk/blob/cmark/Classes/Issues/Comments/Markdown/CMarkParsing.swift). Some huge benefits:
  - All elements are represented w/ enums + data meaning that supported markdown data is represented in entirety when building our app models. 
    - To add more feature support (e.g. images in tables), we first add the enum + parsing in our cmark fork, the compiler will err in GitHawk, then we add feature support.
  - Instead of having a single, mutable builder that we iterate over, we now have different unique builder & logic branch for each root `Element` type
  - Less LOC
  - Functional-ish

App is running and rendering correctly on this branch. Tables are the last TODO.
