### ISSUE TITLE
[Coding convention] Split VC's delegates, datasources in extensions.

### ISSUE THREAD

**Issue by jdisho** [GitHawkApp/GitHawk#1699]
Currently `ViewControllers` conform to many `delegates/dataSources` and in the way it is right now, is not very clear and readable, so I suggest to split them in separate extensions.

What do you think?

**Comment by rnystrom** [comment]
Like new files? IMO that makes them _less_ discoverable b/c now the conformance lives some place else. Is that the proposal?

Do you have some examples that aren't readable?

**Comment by jdisho** [comment]
No, having the extensions inside the same file. Like this: https://github.com/jdisho/GitHawk/commit/10c37dcabfa658a5df313f2f4dbf7927ed9ffb23

Does't look more cleaner @rnystrom ? 😄

**Comment by rnystrom** [comment]
I actually ran into compiler errors following this practice on Swift 3 which is why I avoided using `extension`s. As long as it doesn't change the behavior much I'm fine either way. But would prefer we stick to a single style and then codemod the whole codebase over to the new style at once vs diverging and being inconsistent.

**Comment by SD10** [comment]
I feel like it's the Swifty way to do things, however, you need to watch for two potential hang-ups when conforming via extensions:
1. If we need the property the protocol requires to be a stored property, we can't use extensions because extensions can't have stored properties.
2. If we choose to subclass a controller we can't override the methods declared in an extension.

So for these reasons, I believe it to be cleaner, yes, but less flexible. It may not be the best option for a large codebase that not every contributor understands in great detail.

**Comment by jdisho** [comment]
That is why I asked if it is alright to apply that style in the whole codebase and continue to do so @rnystrom . 

I am aware about the drawbacks when conforming via extensions, but the proposal is only for delegate and dataSource implementations..  @SD10
