### ISSUE TITLE
Special UI for "Sent with GitHawk" in app

### ISSUE THREAD

**Issue by rnystrom** [GitHawkApp/GitHawk#2000]
- Strip this footer in the app
- If we detect it, show a special badge next to the avatar or something cool
- Tap on the small badge and show a popover that says "Sent with GitHawk"

Give people some flair 😄 

h/t @flovilmart

**Comment by rnystrom** [comment]
Need to design a tiny hawk badge

**Comment by flovilmart** [comment]
Cc @governorjosh

**Comment by cieslakdawid** [comment]
I've taken some time to play a bit with the designs you uploaded recently and I made three simple mocks/animations. Badges are in most common format (circular), but I'm not sure if they go well with rectangular pictures.

-  I'm not sure about tapping on the badge - there is not much space, so they would probably be very small and hard to tap. But let's say we can trigger the animation by tapping on the profile picture.
- I feel that popover is a bit too "heavy" component for such a small thing
- @BasThomas  made a good point on Twitter - it's easy to suggest that someone is "GitHub owner/team member" rather than "GitHawk user".  I feel like 2 of the 3 examples below are confusing in this way.

Anyway, maybe someone will find some inspiration in this 🎉😊

![badge_githawk mov](https://user-images.githubusercontent.com/4325222/43370990-4b535c9e-9389-11e8-9522-d0fc3dd9afe6.gif)

**Default View:**

![basdge_screen_1](https://user-images.githubusercontent.com/4325222/43371001-83988a34-9389-11e8-8edf-6a0ccba1f152.png)

**During Animation:**

![basdge_screen_2](https://user-images.githubusercontent.com/4325222/43371065-a774c16a-938a-11e8-837e-1db87dfc7d12.png)

**Sketch Files + Movie ^ in video format:**

[Sketch_and_Movie.zip](https://github.com/GitHawkApp/GitHawk/files/2239222/Sketch_and_Movie.zip)

**Comment by flovilmart** [comment]
I like the last one, with the grayed `via GitHawk 🐦` , it's subtle and conveys it well

**Comment by rnystrom** [comment]
@cieslakdawid WOW! These are so cool! I'm loving the badge w/ a small drop shadow. Going to try implementing a few of these.

And the animations are 🔥, def going to see if we can make some of these happen.
