### ISSUE TITLE
Can’t subscribe/unsubscribe ?

### ISSUE THREAD

**Issue by Huddie** [GitHawkApp/GitHawk#2273]
Steps to reproduce:

In inbox click the speaker icon to flip its state
Pull down to refresh.

The icon is back to its previous state

Anyone else?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
So it comes from this line:

https://github.com/GitHawkApp/GitHawk/blob/8452d73ab9aab9db3891dce102c4b1574acc95d0/Classes/Notifications/Notification%2BNotificationViewModel.swift#L44

I guess the issue is that the notification hasn't been read yet, so it won't disappear. The behavior could be that marking this _also_ marks the notification read? There isn't any other real way to get "watching" status from the V3 API. I guess we could also fetch this info in the GraphQL request for the issue.

**Comment by ijm8710** [comment]
Question as it’s “semi” related. Is there, conceptually a way to unmark a marked item in your inbox as read to add back to active badge count.

**Comment by rnystrom** [comment]
@ijm8710 Sadly there's not 😢 I wish there were so I could unmark things
