### ISSUE TITLE
Issue Dashboard

### ISSUE THREAD

**Issue by Huddie** [GitHawkApp/GitHawk#2413]
Issue dashboard is a nice way to keep track of the issues you're assigned/created. 
This differs from notifications since those appear only when something occurs in the thread. 

Currently, you may bookmark issues you're assigned to in order to keep track of them. 

<img src=https://user-images.githubusercontent.com/10662471/48170808-1b593300-e2c7-11e8-8491-00a7503135b1.gif width=200>

What's happening in the gif:

- Open issue dashboard, nothing shows up (I'm not assigned to any issues)
- I think went and assigned myself to a task
- Refreshed the view and saw the issue

**Comment by rnystrom** [comment]
Sorry I’m a little confused. What’s happening here? Is this a new feature proposal?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
Ya. It’s GitHubs issue Dashboard 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Lol I didn’t know this was a thing! We used to have a seg control but cycling through unread and everything was weird. Maybe we can give it another try.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
Oh ya! I just saw it on github recently and thought it would be nice if GitHawk could get it.

Inbox is nice cause it tells you something changed, but you can’t keep track of the issues your supposed to be working on or you subscribed to.

I think subscribed and assigned are the 2 most interesting ones. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
Oh ya! I just saw it on github recently and thought it would be nice if GitHawk could get it.

Inbox is nice cause it tells you something changed, but you can’t keep track of the issues your supposed to be working on or you subscribed to.

I think subscribed and assigned are the 2 most interesting ones. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
#1265 would closed by this 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Revisiting after seeing this on the Twitter thread. Here's an idea for the inbox redesign (#2497):

- Keep inbox list as-is
- Title view is the same dropdown control we use in issues, etc
- Tap the control to show a ContextMenu with a sectioned list:
  - "Me"
    - Inbox
    - Mentioned
    - Created
    - Assigned
  - "Repos" (should be a list of subbed/watched repos, NOT the lazy-filtering we do today)
    - GitHawk
    - IGListKit
    - etc
- Checkmark on w/e you have selected
- Tap a thing to dismiss the menu and update the inbox (don't push a vc)
- (_stretch_) Put a settings menu that lets you change the default inbox to one of the "Me" boxes

**Comment by Huddie** [comment]
Love it. 

So we don’t pull all issues then filter. We make specific calls getting the appropriate issues each time the user updates? 


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
The issue Dashboard above uses https://developer.github.com/v3/issues/#list-issues with the filtering parameter. That’s what we’re going for ya?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
@Huddie ya exactly. You can toggle what "mode" your inbox is in: one of the viewer-filters, a specific repo, or the master list.

**Comment by ijm8710** [comment]
Stellar!

1. I think this would be a great time to coincide incorporating an open/closed/all toggle. It would have relevance here and also be a great port on the search tab as well as the current implementation doesn’t feel as natural.
2. I could see value to an additional “me” option for commented on (commenter:username)
3. Obviously this would be a growing project, but do you eventually see this implementing the [per-repo inbox logic](https://github.com/GitHawkApp/GitHawk/issues/2177#issuecomment-441406652) or is this an alternative to that?

**Comment by Huddie** [comment]
@rnystrom cool that’s how I was thinking about it with the Issue Dashboard. I think it makes a lot of sense and putting in a drop down on the Nav Bar keeps the style consistent with other parts of the app. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SD10** [comment]
I'm pretty inactive in the OS community right now but def lurking this thread. I can only offer a unique perspective that I actually haven't used GitHawk for maybe a month now -- through no fault of GitHawk. It's GitHub notifications that just aren't scaling for my needs.

I can +1 the idea of a context menu for filters. 
> - Inbox
> - Mentioned
> - Created
> - Assigned

Additionally, if there's a way to filter by merged PRs that would be a huge help too. For context, I often have to subscribe to a codebase just to be aware of people merging things without my review.

With some of these filters, I think GitHawk could help me regain control of notifications because I wouldn't open the app to a giant inbox sorted by event date.

Thanks for all the awesome work you guys have done 💯

**Comment by rnystrom** [comment]
1. Is for repo issue/PRs, not inbox
2. Is this not captured in the other filters?
3. Alternative. Per-repo view will have way too complex and confusing of UX because of API paging. Until a new and improved API (maybe GraphQL) launches, it can’t happen.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ijm8710** [comment]
1. I understand that the linked ticket was originally specific to that. But isn’t there relevance to viewing created threads and filtering for open vs closed? Same for the inbox or really any of the me options.
2. Don’t believe so-
- current roadmap:
  - Inbox includes everything subbed (ie i follow all of github activity so I get notified of all activity not just activity I participated in)
  - mentioned would just be threads you were @
  - created is only posts authored
  - Assigned is only threads that you have been assigned to take over issue
- Don’t see any way to filter on all threads that you’ve actually had activity in specifically
3. Understood about the complexity. I was curious your thoughts on slightly enhancing the current setup where each repo can be selected separate but for both unread and all views. Currently I think you can only menu select a specific-repo for the all view. But is there any way to filter the unread inbox so that it repopulates for a selected repo?

**Comment by rnystrom** [comment]
Started hacking on this today. Made some ground, but its a lot more complex than it seems. The API for mention/create/assign/etc issues is **not** a notification endpoint. So there's no "read" or "unread" status. It's a V3 API (there _is_ a GraphQL API as well).

This means we have to create a totally new request+display pipeline for it (section controllers, cells). Not impossible, just changes the UX quite a bit.

![simulator screen shot - iphone xs - 2018-12-02 at 20 35 04](https://user-images.githubusercontent.com/739696/49348155-ce703e80-f671-11e8-949b-74f5a540f36e.png)

![simulator screen shot - iphone xs - 2018-12-02 at 20 36 06](https://user-images.githubusercontent.com/739696/49348174-ea73e000-f671-11e8-9563-06ea5bb3cf56.png)

**Comment by rnystrom** [comment]
- [Notifications list API](https://developer.github.com/v3/activity/notifications/#list-your-notifications)
- [V4 issue filters](https://developer.github.com/v4/input_object/issuefilters/)
- [V3 issues](https://developer.github.com/v3/issues/#list-issues)

**Comment by Huddie** [comment]
Ya, I was using V3 issues. This looks amazing.

**Comment by ijm8710** [comment]
Curious, what’s the difference between subscribed and inbox? This does look awesome though

**Comment by rnystrom** [comment]
That’s a good question, I’m not totally sure. We might be able to drop that one tbh.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ijm8710** [comment]
For consistency with GitHub it might even make sense to do unread notifications with a bell icon. Of the two you have I think subscribed and it’s icon is more visually appealing than inbox though.

Did my comment make sense that it would be nice to have a view that encompasses participating either as comments or comments+authored as currently none of the options encompass a filter for threads you’ve participated in but didn’t necessarily start

**Comment by j-f1** [comment]
How about having the repo filter as a separate button so people can select a combination of e. g. mentioned and a specific repo?

**Comment by Huddie** [comment]
Subscribed: All thread your subscribed to
Inbox: Notifications (could be a thread your subscribed to, watching, mentioned in)

Subscribed would show all those your subscribed to regardless if there was a recent notification/activity or not.
Inbox will show only those threads which your subscribed to (or watching <~ another difference) and have current activity (there was a notification)


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ijm8710** [comment]
@Huddie but for #2482, if you watch a repo/thread that you may have never been mentioned or commented in, wouldn’t that still show as having an active subscription? Meaning for some reason I feel subscribed picks up watching...

**Comment by ijm8710** [comment]
@Huddie let me try phrasing it a different way with a simple question. Since you’re talking about the difference between inbox and subs, I know we have “notifications” on native GitHub which can be peruses unread/read. Is there another *native* list view on GitHub that has a listing to compliment to essentially mimic the contrast you mention here?

**Comment by Huddie** [comment]
Issue Dashboard ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ijm8710** [comment]
Yes and I see the issue dashboard has assigned, created, mentioned, but in the same way that unread notifications hits on how either inbox or subscribed works, what aggregate view on issue dashboard hits on the other. I’m basically asking is there a list-set in it that is different from anything else we see implemented in Ryan’s wip

**Comment by Huddie** [comment]
If your asking if there are threads subscribed to that you didn’t create, mentioned in or assigned. The answer is yes. Whether or not GitHub has this list visible I’m not sure. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ijm8710** [comment]
My whole point is that it’d be nicer to have a participated list and a notification list (read vs all) than having both inbox and subscriptions...imo of course. And to perhaps have per-repo as a separate button for it as j-fi suggested

**Comment by Huddie** [comment]
Why was subscribed dropped? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Overlap with traditional notifications 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ijm8710** [comment]
Excellent work Ryan! I have some comments/requests of course but for a bit I just want to let this soak in and appreciate the awesome work on it since I know you’ve felt a little burnt out and looks like you took a tiny hiatus hopefully to recharge a bit with this hobby! Good job with the dashboard suggestion too @Huddie
