### ISSUE TITLE
Selecting the currently selected issue reloads the detail view. 

### ISSUE THREAD

**Issue by shaps80** [GitHawkApp/GitHawk#244]
Very low priority tbh just adding for posterity because it’s a less than ideal UX

Version 1.5.0 (1330)
Device: iPad7,3 (iOS 11.0)

**Comment by rnystrom** [comment]
Ya I've noticed this, it's wasteful. Easy fix.

**Comment by wolffan** [comment]
Tried fixing this, but not sure this is related as much to GitHawk or to IGList...

**Comment by BasThomas** [comment]
Shouldn’t be related to `IGListKit` 👍

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Yup, the selected and visible VC state needs to be tracked. This doesn’t bother me that much at all tbh. Unless we can come up with a _super clean_ solution, it’s not worth spending much time on.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by wolffan** [comment]
I had something, but the enum on the presented controller had me confused (when you switch for number or string id, the number is a hash).

The idea was to prevent the controller from being presented, because it's re-created every time. Without much success, but if you think it's the right call i'll keep on it (btw the controller I believe was the Notification one)

**Comment by rob-nash** [comment]
Hi,

I am struggling to understand this one. 

I'm new to the project and unfamiliar with the App.

When you say 'the currently selected issue' and 'detail view', what are you referring to exactly?  An issue on a GitHub repo?

**Comment by rob-nash** [comment]
Oh, you mean an inbox item?

**Comment by rob-nash** [comment]
Ok, have fixed this. Will submit PR in a moment. Looking forward to review.
