### ISSUE TITLE
Add review status to PR summary

### ISSUE THREAD

**Issue by rnystrom** [GitHawkApp/GitHawk#254]
Would love to know when things are ready for merge or if changes are needed

**Comment by Sherlouk** [comment]
Looking at V4 API we have two nodes we're probably interested in:

https://developer.github.com/v4/reference/object/pullrequest/
"reviews" which will let us see if it's had a review and if any have failed
and "reviewRequests" which will let us see if the logged in user has been asked to review the PR

The UI could have various messages, proposing:
"Changes Requested"
"Updates Made"? - If the PR has been updated since the user declined it
"Awaiting Review"
"Approved"

**Comment by BasThomas** [comment]
Do we not have this?
