### ISSUE TITLE
In app notifications

### ISSUE THREAD

**Issue by Huddie** [GitHawkApp/GitHawk#2540]
Is there anyway to notify users who are currently in app when a new notification arrives. Right now must go to inbox and refresh to see if you got a new notification.
Or does this require a server?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Should be possible!

**Comment by rnystrom** [comment]
This requires some significant thought/work if we wanted it. Right now notifications only arrive on manual refresh (or refresh after a certain period in the background). "Push" notifications are only displayed from a background task, so the app has to be backgrounded.

If we wanted to go this route, we need:

- An in-app UI to do notifications
- A new fetch mechanism that polls for updates and then shows notifications

I'm going to close as its a fair bit of work and I haven't heard this asked by anyone else (and I personally don't want it). Feel free to re-open if feel strongly otherwise.
