### ISSUE TITLE
"Mentioned" issues are not sorted by date

### ISSUE THREAD

**Issue by BasThomas** [GitHawkApp/GitHawk#2649]
Referencing #2612

**Describe the bug**
Take a look at only mentioned issues, and observe they are not sorted by date

**To Reproduce**
1. Go to "Inbox"
2. Click on Inbox
3. Click on Mentioned

**Expected behavior**
A list of issues that is sorted by date, latest on top

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/4190298/53221907-d4bbf880-366b-11e9-8522-4caf673f2f6b.jpeg)

Request:

```
curl -v -X GET 'https://api.github.com/issues?access_token=123filter=mentioned&page=1&per_page=50' -H 'User-Agent: Freetime/1.27.1 (com.whoisryannystrom.freetime; build:1546622353; iOS 12.1.4) Alamofire/4.4.0' -H 'Accept-Language: en-DE;q=1.0, de-DE;q=0.9, nl-DE;q=0.8' -H 'Authorization: token 7e713728cee1b78872817efad46a940ce65af232' -H 'Accept: application/vnd.github.merge-info-preview+json' -H 'Accept-Encoding: gzip;q=1.0, compress;q=0.5' -H 'Cookie: logged_in=no;' 
```

**Comment by akarataev** [comment]
I'll take a look at this, if nobody is against.

**Comment by ijm8710** [comment]
@BasThomas I think this is slightly different then the ticket I opened that you referenced. My older ticket focused on the aggregation of all the issues within a specific filter type, aka created or mentioned.

Your ticket revolves around time stamps. Assuming we are identifying the same thing, what I noticed is that GitHub issue tickets will not fall in chronological order specifically when you yourself are the only one post a new comment. Unless someone else comments after, the timestamp will update to newer but since there is no new activity for you to review, it doesn’t bump it to the top. I actually wish it sorted chronologically regardless but it’s not an app error but just how GitHub handles things. I have even emailed them directly about this requesting that they added an option to sort chronologically for all tickets, even if you are the only updater. 

If we are on the same page here and you agree, I would love you to send GitHub another ticket on this to add visibility to what I wrote and hopefully influence them more to accommodate. If it’s something different, apologies and carry on.

**Comment by BasThomas** [comment]
Interesting, @ijm8710. It feels like it would be behaving as expected then, as of now? It’s a bit confusing though. I’m not sure what the UX would look like, but GitHawk could add it as an option to sort by “last updated”? What do you think?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ijm8710** [comment]
[Sounds like Ryan was against it](https://github.com/GitHawkApp/GitHawk/issues/2574#issuecomment-451292917)

If you and I are on same page of having it sort chronologically regardless of if last update was by “you” or “not you”, the best way to drive it would be to nudge GitHub like I did. Like I said, I would love another voice to echo the request I already made with them!

**Comment by ijm8710** [comment]
Ps any idea if Ryan just wanted a little break or if he was trying to back away from this in general. Either way I’m super appreciate of the app and the hard work that went into it, was just curious if you expect it to pop back in whenever he so chooses (which is obv completely his call) or if it would make sense to have more people at his admin level to perhaps keep driving innovation align to what he would want

**Comment by BasThomas** [comment]
All I know is that he's not active at the moment.

**Comment by akarataev** [comment]
@BasThomas hello,
 
Please see #2663 how you will have the opportunity.
