### ISSUE TITLE
Open Safari links in githawk

### ISSUE THREAD

**Issue by misanthrophy** [GitHawkApp/GitHawk#2738]
Hi,

Is there a chance, if I open a github link in safari, that it automatically opens it in githawk? Like youtube, Instagram and other apps are doing?

**Comment by Sherlouk** [comment]
Hi @misanthrophy,

What I believe you're referring to there is a technology called Universal Linking where Apple will open a native app (if installed) for certain compatible URLs.

Unfortunately this requires a file to be uploaded to the website itself in order to redirect users to the native app. As we don't own or have any association with GitHub we are unable to do this.

There have been some attempts in the past to do something a bit different - for example using an action extension demonstrated [here](https://github.com/GitHawkApp/GitHawk/pull/2134).

We do however have support for [Opener](https://www.opener.link/) which lets you easily open a URL in a variety of apps.

Another possible solution would be to introduce our own redirect URL. For instance if I shared a URL `https://githawk.com/Owner/Repo/issues/1` then this could redirect users to the app, if installed, or redirect to `github.com` if not installed. 

This would only work for these URLs though, benefitting from everyone using them which would likely mean an inconsistent experience not ideal.

**Comment by BasThomas** [comment]
As @Sherlouk mentioned, this is unfortunately not possible...
