### ISSUE TITLE
Inbox Issues

### ISSUE THREAD

**Issue by JavaGuy12** [GitHawkApp/GitHawk#2781]
Hi! Loving this UI. However, my inbox has messages and I can’t seem to see them. I also received a github email, but no push notification from GitHawk. GitHawk has all Oauth stuff and has a key that I set up for my 2FA. Please help! Thanks.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.27.2 (1546696737)
Device: iPhone 8 (iOS 13.0)
TestFlight: false
</pre>
</details>

**Comment by BasThomas** [comment]
Hi @JavaGuy12!

It's not entirely clear to me what the issue is — are you both not seeing any issues/pull requests in your inbox, nor getting push notifications? Or is it one of the two?

Regarding the inbox: can you check if all (required) organizations are accessible to GitHawk?
Regarding the notifications: these are not push, but pull, and the system (iOS) decides when it can give GitHawk time to check. That means notifications might be delayed.

Let me know if that helps or if you have any more questions!

**Comment by JavaGuy12** [comment]
Yeah. I’ve got that done. I’ll have to wait till ya write me back to see if it works.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by JavaGuy12** [comment]
I haven't been getting these pull notifications nor anything in my inbox. GitHawk has access to pretty much everything it has asked for. Thanks for your help.
