### ISSUE TITLE
Notifications are slow to come in if they ever make it.

### ISSUE THREAD

**Issue by JoshuaHolme** [GitHawkApp/GitHawk#2787]
Notifications seem to take forever to come in, if they ever get there. I get email notifications from github and it can sometimes take up to 15 minutes to get the notification in GitHawk without seeking out the issue that I was tagged in under the “All” menu.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.27.2 (1546696737)
Device: iPad8,5 (iOS 13.0)
TestFlight: false
</pre>
</details>

**Comment by Huddie** [comment]
Hey Joshua!
GitHawk has a unique way of implementing notifications so that no server and device tokens are necessary. 
It does this by checking in the background if there is any new content and if so, creates a local notification .

Background app refreshes happen on the system level, not app level, so we don’t have control over when the refresh will occur but it should happen around once every hour the longest. 

That being said, if your on power saver mode, it won’t occur and that can be why your not ever receiving a notification.

- Ehud 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
#2748 dupe

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
