### ISSUE TITLE
Separate components into small pods/libs

### ISSUE THREAD

**Issue by rnystrom** [GitHawkApp/GitHawk#512]
I created the @GitHawkApp org (empty atm) to start storing stuff. Inspired by @BasThomas from #483 ([comment](https://github.com/rnystrom/GitHawk/pull/483#issuecomment-334179617)) to move small libs into their own pods.

### Pros:

- Other ppl can pull them in
- We can version our own stuff

### Cons:

- Lots of overhead
- Could slow us down significantly

### Existing lib candidates

I think once we have things that are in stable shape, we could put them in their own libs. Some starters that I can think of:

- [Tab bar delegate](https://github.com/rnystrom/GitHawk/blob/master/Classes/View%20Controllers/TabBarControllerDelegate.swift) for single and double tapping on items
- [Split view VC delegate](https://github.com/rnystrom/GitHawk/blob/master/Classes/View%20Controllers/SplitViewControllerDelegate.swift) for expanding/collapsing, showing details, pushing onto nav, etc
- [Rating prompt](https://github.com/rnystrom/GitHawk/tree/master/Classes/Systems/Rating) for native **and** IGListKit inline prompt, as well as managing spacing in between
- [Attributed string](https://github.com/rnystrom/GitHawk/blob/master/Classes/Systems/NSAttributedStringSizing.swift) for sizing and rendering along w/ [its view](https://github.com/rnystrom/GitHawk/blob/master/Classes/Views/AttributedStringView.swift) (gesture handling)
- [Markdown parsing](https://github.com/rnystrom/GitHawk/blob/master/Classes/Issues/Comments/Markdown/CommentModelsFromMarkdown.swift) along w/ MMMarkdown changes
  - This is pretty hairy tho: models, views, IGListKit stuff....
- [Spinner cell](https://github.com/rnystrom/GitHawk/blob/master/Classes/Systems/SpinnerSectionController.swift) in IGListKit. This is super super common, nice to generalize
- ["Feed" setup](https://github.com/rnystrom/GitHawk/blob/master/Classes/Systems/Feed.swift)
  - Along w/ [base list VC](https://github.com/rnystrom/GitHawk/blob/master/Classes/View%20Controllers/BaseListViewController.swift)
- [Smart cell deselection](https://github.com/rnystrom/GitHawk/blob/master/Classes/View%20Controllers/UIViewController%2BSmartDeselection.swift) based off of raiz labs

**Comment by BasThomas** [comment]
FWIW, I think the Split view VC thing might still need some work. Would be nice if it could help us with not forgetting navigation bars and stuff (like in the current TF)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Ya good point, it should be helping w/ that more for sure.

**Comment by Sherlouk** [comment]
So unwelcomed opinion over here: I'm personally not a fan of completely separating components that are not on their own really re-usable, testable, configurable and convenient especially where most people will want something *slightly* different.

I feel valid candidates are proper forks of SlackTextViewController, etc where we already have made changes.

Our own version of toaster is also great because on it's own it provides something, is re-usable and is testable on it's own.

An alternative here which I've been practicing at work and has had relatively great success is internal sub-projects. Can treat them likes groups for the most part to have certain more self-contained modules, but they're independently testable, and has the added benefit of not being re-compiled unless they're changed.

I'm personally not a fan of this pick'n'mix approach to pods where everything as small as a single class can come is an extra dependency. Adds a large wall of complexity when trying to do sweeping changes.

**Comment by rnystrom** [comment]
@Sherlouk yup, that's generally my approach too. A lot of these are pretty tiny, so not really worth the investment unless they are packaged w/ tests and whatnot.

**Comment by BasThomas** [comment]
Yep, feel the same @Sherlouk. Should definitely not go overboard with this.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Test

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Think this can be closed at this point ^^
